"""empty message

Revision ID: 055a524569f3
Revises: 7498f4c2226d
Create Date: 2024-06-25 02:46:48.695136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055a524569f3'
down_revision = '7498f4c2226d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronic_invoice', schema=None) as batch_op:
        batch_op.alter_column('number_cardID',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronic_invoice', schema=None) as batch_op:
        batch_op.alter_column('number_cardID',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
