"""empty message

Revision ID: 17fbb86a4bac
Revises: ff94963ebb6b
Create Date: 2024-07-01 20:38:10.946671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fbb86a4bac'
down_revision = 'ff94963ebb6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modality')
    with op.batch_alter_table('new_course', schema=None) as batch_op:
        batch_op.drop_constraint('new_course_modality_id_fkey', type_='foreignkey')
        batch_op.drop_column('modality_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modality_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('new_course_modality_id_fkey', 'modality', ['modality_id'], ['id'])

    op.create_table('modality',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='modality_pkey')
    )
    # ### end Alembic commands ###
