"""empty message

Revision ID: 9524b2ab49cc
Revises: b715d5d00e45
Create Date: 2024-06-25 02:10:03.026866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9524b2ab49cc'
down_revision = 'b715d5d00e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iban_account', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('professor_payment_iban_acount_key', type_='unique')
        batch_op.create_unique_constraint(None, ['iban_account'])
        batch_op.drop_column('iban_acount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iban_acount', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('professor_payment_iban_acount_key', ['iban_acount'])
        batch_op.drop_column('iban_account')

    # ### end Alembic commands ###
