"""empty message

Revision ID: b715d5d00e45
Revises: c2c082eb918e
Create Date: 2024-06-25 01:48:39.433480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b715d5d00e45'
down_revision = 'c2c082eb918e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('cardID_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('number_cardID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('canton',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('distric',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('electronic_invoice', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('cardID_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('number_cardID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('canton',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('distric',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('modality', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('cardID_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('number_cardID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('canton',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('distric',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('professor_payment', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('iban_acount',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('cardID_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('number_cardID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('canton',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('distric',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('student_payment', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('mount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_payment', schema=None) as batch_op:
        batch_op.alter_column('mount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('distric',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('canton',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('number_cardID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cardID_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('professor_payment', schema=None) as batch_op:
        batch_op.alter_column('iban_acount',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('distric',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('canton',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('number_cardID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cardID_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('modality', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('electronic_invoice', schema=None) as batch_op:
        batch_op.alter_column('distric',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('canton',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('number_cardID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cardID_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('distric',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('canton',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('number_cardID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cardID_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
