"""empty message

Revision ID: edcc920d123b
Revises: a5a28c1bf076
Create Date: 2024-06-29 20:28:32.293767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edcc920d123b'
down_revision = 'a5a28c1bf076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=20), nullable=True))

    # Migrate existing data to set non-null values for user_type
    op.execute("UPDATE professor SET user_type = 'profesor' WHERE user_type IS NULL")

    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.alter_column('user_type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
